/**
 * ---------------------------------------------------------------------------
 * 🚨🚨  AUTO-GENERATED FILE — DO NOT EDIT MANUALLY  🚨🚨
 * ---------------------------------------------------------------------------
 *
 * Generated by:
 *   scripts/genomodal.ts
 *
 * Any manual changes will be overwritten.
 *
 * To update modalsFrom:
 *   1. Add/remove files in src/modalsFrom/
 *   2. Run:
 *        pnpm tsx scripts/genomodal.ts
 *
 * ---------------------------------------------------------------------------
 */

import type { StarknetReactConfigType } from "../modalsFrom/starknetReact";

export type ModalConfigType =
  | { from: "starknetReact"; options: StarknetReactConfigType };
