/**
 * ---------------------------------------------------------------------------
 * ⚠️  AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
 * ---------------------------------------------------------------------------
 *
 * Generated by:
 *   scripts/genokit.ts
 *
 * Any manual changes will be overwritten.
 *
 * To update kits:
 *   1. Add/remove files in src/kits/
 *   2. Run:
 *        pnpm tsx scripts/genokit.ts
 *
 * ---------------------------------------------------------------------------
 */

import type { ConnectkitConfig } from "../kits/connectkit";
import type { ReownConfig } from "../kits/reown";

export type EvmKitConfigType =
  | { name: "connectkit"; config: ConnectkitConfig }
  | { name: "reown"; config: ReownConfig };
