import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

/* ---------------------------------- */
/* Resolve Paths */
/* ---------------------------------- */

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const kitsDir = path.resolve(__dirname, "../src/kits");
const typesFile = path.resolve(__dirname, "../src/types/kit.ts");

/* ---------------------------------- */
/* Read Kit Files */
/* ---------------------------------- */

const kitFiles = fs.readdirSync(kitsDir);

const kitNames = kitFiles
  .filter((file) => file.endsWith(".ts") && !file.endsWith(".d.ts"))
  .map((file) => path.basename(file, ".ts"));

/* ---------------------------------- */
/* Warning Header */
/* ---------------------------------- */

const warningMessage = `/**
 * ---------------------------------------------------------------------------
 * ⚠️  AUTO-GENERATED FILE — DO NOT EDIT MANUALLY
 * ---------------------------------------------------------------------------
 *
 * Generated by:
 *   scripts/genokit.ts
 *
 * Any manual changes will be overwritten.
 *
 * To update kits:
 *   1. Add/remove files in src/kits/
 *   2. Run:
 *        pnpm tsx scripts/genokit.ts
 *
 * ---------------------------------------------------------------------------
 */`;

/* ---------------------------------- */
/* Imports */
/* ---------------------------------- */

const imports = kitNames
  .map(
    (name) =>
      `import type { ${capitalize(name)}Config } from "../kits/${name}";`,
  )
  .join("\n");

/* ---------------------------------- */
/* Union Type */
/* ---------------------------------- */

const unionType =
  kitNames.length > 0
    ? kitNames
        .map((name) => `{ name: "${name}"; config: ${capitalize(name)}Config }`)
        .join(" |\n  ")
    : "never";

/* ---------------------------------- */
/* Final Content */
/* ---------------------------------- */

const content = `${warningMessage}

${imports}

export type EvmKitConfigType =
  | ${unionType};
`;

/* ---------------------------------- */
/* Write File */
/* ---------------------------------- */

fs.writeFileSync(typesFile, content, "utf8");

console.log(
  `✔ Generated kit types → ${typesFile}\n  Kits: ${
    kitNames.length ? kitNames.join(", ") : "none found"
  }`,
);

/* ---------------------------------- */
/* Utils */
/* ---------------------------------- */

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
