import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

/* ---------------------------------- */
/* Resolve Paths                       */
/* ---------------------------------- */

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const modalsDir = path.resolve(__dirname, "../src/modals/from");
const typesFile = path.resolve(__dirname, "../src/modals/index.ts");

/* ---------------------------------- */
/* Read Modal Files                    */
/* ---------------------------------- */

const modalFiles = fs.readdirSync(modalsDir);

const modalNames = modalFiles
  .filter(
    (file) =>
      file.endsWith(".ts") &&
      !file.endsWith(".d.ts") &&
      !file.endsWith(".type.ts"),
  )
  .map((file) => path.basename(file, ".ts"));

/* ---------------------------------- */
/* Warning Header                      */
/* ---------------------------------- */

const warningMessage = `/**
 * ---------------------------------------------------------------------------
 * 🚨🚨  AUTO-GENERATED FILE — DO NOT EDIT MANUALLY  🚨🚨
 * ---------------------------------------------------------------------------
 *
 * Generated by:
 *   scripts/genomodal.ts
 *
 * Any manual changes will be overwritten.
 *
 * To update modals:
 *   1. Add/remove files in src/modals/
 *   2. Run:
 *        pnpm tsx scripts/genomodal.ts
 *
 * ---------------------------------------------------------------------------
 */`;

/* ---------------------------------- */
/* Imports                             */
/* ---------------------------------- */

const imports = modalNames
  .map(
    (name) =>
      `import type { ${capitalize(name)}ConfigType } from "./from/${name}";`,
  )
  .join("\n");

/* ---------------------------------- */
/* Union Type                          */
/* ---------------------------------- */

const unionType =
  modalNames.length > 0
    ? modalNames
        .map(
          (name) =>
            `{ from: "${name}"; options: ${capitalize(name)}ConfigType }`,
        )
        .join(" |\n  ")
    : "never";

/* ---------------------------------- */
/* Final Content                       */
/* ---------------------------------- */

const content = `${warningMessage}

${imports}

export type WalletConfigType =
  | ${unionType};
`;

/* ---------------------------------- */
/* Write File                          */
/* ---------------------------------- */

fs.writeFileSync(typesFile, content, "utf8");

console.log(
  `✔ Generated modal types → ${typesFile}\n  Available modals: ${
    modalNames.length ? `[${modalNames.join(", ")}]` : "none found"
  }`,
);

/* ---------------------------------- */
/* Utils                               */
/* ---------------------------------- */

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
