/**
 * ---------------------------------------------------------------------------
 * 🚨🚨  AUTO-GENERATED FILE — DO NOT EDIT MANUALLY  🚨🚨
 * ---------------------------------------------------------------------------
 *
 * Generated by:
 *   scripts/genomodal.ts
 *
 * Any manual changes will be overwritten.
 *
 * To update modals:
 *   1. Add/remove files in src/modals/
 *   2. Run:
 *        pnpm tsx scripts/genomodal.ts
 *
 * ---------------------------------------------------------------------------
 */

import type { FamilyConfigType } from "./from/family";
import type { ReownConfigType } from "./from/reown";

export type WalletConfigType =
  | { from: "family"; options: FamilyConfigType } |
  { from: "reown"; options: ReownConfigType };
